version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vassoler3910@
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5433:5433"
volumes:
  postgres: